[package]
edition = "2024"
name    = "hyperdep"
version = "0.1.0"

[dependencies]
petgraph = { version = "0.8", optional = true }
semver   = { workspace = true, optional = true }

[features]
default  = ["petgraph", "semver"]
petgraph = ["dep:petgraph"]
semver   = ["dep:semver"]
