[package]
edition = "2024"
name    = "config"
version = "0.1.0"

[dependencies]
etcetera = "^0.11"

serde.workspace   = true
tracing.workspace = true

figment = { version = "^0.10", features = ["env", "toml"] }
gix     = { workspace = true, default-features = false }
